### ISSUE TITLE
Asset pipe line does not work in production

### ISSUE THREAD

**Issue by zpaulovics** [fatfreecrm/ffcrm_app#5]
Hi,
1. I have downloaded your app. It is working in development environment correectly. 
1. Precompiled the assets and tried to use it in production environment. It does not load the assets. Please see the attached file.

Regards,
Zoltan
<img width="768" alt="screen shot 2016-07-11 at 13 46 20" src="https://cloud.githubusercontent.com/assets/884100/16729676/38b0f844-476e-11e6-9eae-40bfba32a042.png">

**Comment by steveyken** [comment]
Check to see if "serve_static_assets" is true in
/config/environments/production.rb

In production, ffcrm is designed to be run by passenger or another hardened
agent which takes care of serving the assets itself.

Regards,
Steve

**Comment by zpaulovics** [comment]
Hi,

I have checked it, and the result is the same. 
If I look into the /public/asssets directory the application-6a98984179...css is there, but the HTTP GET can not find it. I had a try with the none engine version of the software, it works in production serving the assets by the pipe line.

Regads,

Zoltan
